### ISSUE TITLE
[Deprecation] No more NamedBase

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#882]
The `NamedBase` generator is now deprecated. A `Namedbase` generator is only a generator with a `name` arguments. This is equivalent to:

```js
var generators = require('yeoman-generators');

generators.Base.extend({
  constructor: function () {
    Base.apply(this, arguments);
    this.argument('name', { type: String, required: true });
  }
});
```

Ask questions below if you run into issue migrating.

**Comment by andrewconnell** [comment]
Is there an other issue / doc with more information here? Just hit this deprecated message when I ran my tests today and I'm not clear on (1) what the issue is or (2) where the issue is in my code or (3) what I should be doing instead. I use `generators.Base.extend()` & `generators.Base.apply()` in multiple places in my generator, but this deprecated message (`NamedBase constructor is deprecated`) is only showing up one time.

**Comment by SBoudrias** [comment]
At some place you have call `generators.NamedBase`. You can `git grep NamedBase` and find where in your source code.

**Comment by dsebastien** [comment]
@SBoudrias I'm a bit lost, I don't really understand what to change either. Here's my generator code (that's the only file): https://github.com/dsebastien/modernWebDevGenerator/blob/master/app/index.es2015.js

I don't think I use NamedBase anywhere?

**Comment by SBoudrias** [comment]
Ah, just found the culprit. We're referencing `generators.NamedBase` in the core library at import time (to alias it). I'll fix.

**Comment by SBoudrias** [comment]
The false deprecation warning is fixed in https://github.com/yeoman/generator/releases/tag/v0.22.1

**Comment by dsebastien** [comment]
+1, thanks! :)

**Comment by Pickra** [comment]
I just set up yeoman-generator, `v0.22.1`.
Don't use `NamedBase` and only use `module.exports = yeoman.Base.extend({` once.
The only references to `NamedBase` are in the yeoman node_modules.
Still getting the deprecated message.
What am I missing?

**Comment by tyrsius** [comment]
The [authoring](http://yeoman.io/authoring/) docs still instruct you to used NamedBase.
